---
abstract: 'Install modules required for Pugs-like smoke system'
author:
  - 'Gaal Yahas, C<< <gaal at forum2.org> >>'
distribution_type: module
generated_by: 'Module::Install version 0.76'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-Smoke
no_index:
  directory:
    - inc
    - t
recommends:
  YAML::Syck: 0.85
requires:
  Best: 0.06
  MKDoc::XML: 0
  Petal: 0
  Test::Harness::Results: 0
  Test::TAP::HTMLMatrix: 0
  Test::TAP::Model: 0.08
  Time::Out: 0
  URI: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.19
